
<MainScreen>:
    canvas.before:
        Color:
            rgba: 0,0,0,.4
        Rectangle:
            size: self.size
            pos: self.pos
    MDBoxLayout:
        MDLabel:
            text: "Your are now on the main screen! Wow!!!"
            valign: 'middle'
            halign: 'center'
            theme_text_color: 'Custom'
            text_color: 1,.6,1,1
            font_style: 'H3'
